# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.IntegerField(default=0)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaga.Patient'),
        ),
    ]
